# ============================================================================
# pnpm-workspace.yaml
# 경로: d:/app/pnpm-workspace.yaml
# 작성일: 2025-12-19
# ============================================================================
#
# [파일 설명]
# pnpm 모노레포 워크스페이스 설정 파일입니다.
# 이 파일은 프로젝트 내에서 관리할 패키지들의 경로를 정의합니다.
#
# [주요 기능]
# - apps/*: Shell 앱 (메인 컨테이너)
# - services/*/web: 각 도메인별 마이크로 프론트엔드 서비스
# - packages/*: 공통 패키지 (@erp/ui, @erp/shared, @erp/config)
#
# [사용 예시]
# $ pnpm install  # 모든 워크스페이스 패키지 의존성 설치
# $ pnpm --filter shell dev  # shell 앱만 개발 서버 실행
# $ pnpm --filter @erp/ui build  # @erp/ui 패키지만 빌드
# ============================================================================

packages:
  # Shell 앱 (메인 컨테이너, 포트 3000)
  - "apps/*"
  
  # 마이크로 프론트엔드 서비스들
  # 각 서비스는 독립적으로 배포 가능한 Next.js 앱입니다
  - "services/*/web"
  
  # 공통 패키지
  # - @erp/ui: 디자인 시스템 컴포넌트
  # - @erp/shared: 비즈니스 로직, API 클라이언트
  # - @erp/storybook: 컴포넌트 문서화
  - "packages/*"
  
  # Config 하위 패키지들 (ESLint, Prettier, TypeScript 설정)
  - "packages/config/*"

